#!/bin/sh

/home/vijay/.local/bin/set_wallpaper /home/vijay/Pictures/Random/wallhaven-8oky1j.jpg &
# /home/vijay/.local/bin/dwm_bar &
slstatus &
xcompmgr &
dunst &
xset r rate 300 50 &
sxhkd &
numlockx on
bluetoothctl power on &
bluetoothctl discoverable on &
bluetoothctl scan on &
bluetoothctl pairable on &
xmodmap ~/.config/xmodmap/Xmodmap &
unclutter &

xrandr --output VGA-1 --mode 1440x900 --rate 74.98
xrandr --output HDMI-1 --mode 1920x1080 --rate 74.98

exec dwm > /dev/null 2>&1
